server:
  port: 8888
  
spring: 
  application:
    name: BigTouService
    
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/micro-service?useSSL=true
    username: root
    password: root
    
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
  http: 
    multipart: 
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
